//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionErpEntity
{
    using System;
    
    
    public sealed class BrakeBRBEntity
    {
        
        private int _idx;
        
        private string _brb001;
        
        private string _brb002;
        
        private string _brb003;
        
        private string _brb004;
        
        private DateTime? _brb005;
        
        private int _brb006;
        
        private string _brb007;
        
        private int? _brb008;
        
        private string _brb009;
        
        private string _brb010;
        
        private string _brb011;
        
        private string _brb012;
        
        private string _brb013;
        
        private string _brb014;
        
        private string _brb015;
        
        private string _brb016;
        
        private string _brb017;
        
        private string _brb018;
        
        private string _brb019;
        
        private string _brb020;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 条码
        /// </summary>

        public string BRB001
        {
            get
            {
                return this._brb001;
            }
            set
            {
                this._brb001 = value;
            }
        }

        /// <summary>
        /// 工步
        /// </summary>

        public string BRB002
        {
            get
            {
                return this._brb002;
            }
            set
            {
                this._brb002 = value;
            }
        }

        /// <summary>
        /// 记录信息
        /// </summary>

        public string BRB003
        {
            get
            {
                return this._brb003;
            }
            set
            {
                this._brb003 = value;
            }
        }

        /// <summary>
        /// 员工姓名
        /// </summary>

        public string BRB004
        {
            get
            {
                return this._brb004;
            }
            set
            {
                this._brb004 = value;
            }
        }

        /// <summary>
        /// 填写时间
        /// </summary>

        public DateTime? BRB005
        {
            get
            {
                return this._brb005;
            }
            set
            {
                this._brb005 = value;
            }
        }
        
        /// <summary>
        /// 序号
        /// </summary>
                 
        public int BRB006
        {
            get
            {
                return this._brb006;
            }
            set
            {
                this._brb006 = value;
            }
        }

        /// <summary>
        /// 记录数据
        /// </summary>

        public string BRB007
        {
            get
            {
                return this._brb007;
            }
            set
            {
                this._brb007 = value;
            }
        }

        /// <summary>
        /// 最终工时
        /// </summary>

        public int? BRB008
        {
            get
            {
                return this._brb008;
            }
            set
            {
                this._brb008 = value;
            }
        }
        
        // 
        public string BRB009
        {
            get
            {
                return this._brb009;
            }
            set
            {
                this._brb009 = value;
            }
        }
        
        // 
        public string BRB010
        {
            get
            {
                return this._brb010;
            }
            set
            {
                this._brb010 = value;
            }
        }
        
        // 
        public string BRB011
        {
            get
            {
                return this._brb011;
            }
            set
            {
                this._brb011 = value;
            }
        }
        
        // 
        public string BRB012
        {
            get
            {
                return this._brb012;
            }
            set
            {
                this._brb012 = value;
            }
        }
        
        // 
        public string BRB013
        {
            get
            {
                return this._brb013;
            }
            set
            {
                this._brb013 = value;
            }
        }
        
        // 
        public string BRB014
        {
            get
            {
                return this._brb014;
            }
            set
            {
                this._brb014 = value;
            }
        }
        
        // 
        public string BRB015
        {
            get
            {
                return this._brb015;
            }
            set
            {
                this._brb015 = value;
            }
        }
        
        // 
        public string BRB016
        {
            get
            {
                return this._brb016;
            }
            set
            {
                this._brb016 = value;
            }
        }
        
        // 
        public string BRB017
        {
            get
            {
                return this._brb017;
            }
            set
            {
                this._brb017 = value;
            }
        }
        
        // 
        public string BRB018
        {
            get
            {
                return this._brb018;
            }
            set
            {
                this._brb018 = value;
            }
        }
        
        // 
        public string BRB019
        {
            get
            {
                return this._brb019;
            }
            set
            {
                this._brb019 = value;
            }
        }
        
        // 
        public string BRB020
        {
            get
            {
                return this._brb020;
            }
            set
            {
                this._brb020 = value;
            }
        }
    }
}
