//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionErpEntity
{
    using System;
    
    
    public sealed class BrakeBRAEntity
    {
        
        private int _idx;
        
        private string _bra001;
        
        private string _bra002;
        
        private string _bra003;
        
        private string _bra004;
        
        private string _bra005;
        
        private string _bra006;
        
        private string _bra007;
        
        private string _bra008;
        
        private string _bra009;
        
        private string _bra010;
        
        private string _bra011;
        
        private string _bra012;
        
        private string _bra013;
        
        private string _bra014;
        
        private string _bra015;
        
        private string _bra016;
        
        private string _bra017;
        
        private string _bra018;
        
        private string _bra019;
        
        private string _bra020;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 条码
        /// </summary>

        public string BRA001
        {
            get
            {
                return this._bra001;
            }
            set
            {
                this._bra001 = value;
            }
        }

        /// <summary>
        /// 品号
        /// </summary>

        public string BRA002
        {
            get
            {
                return this._bra002;
            }
            set
            {
                this._bra002 = value;
            }
        }

        /// <summary>
        /// 品名
        /// </summary>

        public string BRA003
        {
            get
            {
                return this._bra003;
            }
            set
            {
                this._bra003 = value;
            }
        }

        /// <summary>
        /// 规格
        /// </summary>

        public string BRA004
        {
            get
            {
                return this._bra004;
            }
            set
            {
                this._bra004 = value;
            }
        }
        
        // 
        public string BRA005
        {
            get
            {
                return this._bra005;
            }
            set
            {
                this._bra005 = value;
            }
        }
        
        // 
        public string BRA006
        {
            get
            {
                return this._bra006;
            }
            set
            {
                this._bra006 = value;
            }
        }
        
        // 
        public string BRA007
        {
            get
            {
                return this._bra007;
            }
            set
            {
                this._bra007 = value;
            }
        }
        
        // 
        public string BRA008
        {
            get
            {
                return this._bra008;
            }
            set
            {
                this._bra008 = value;
            }
        }
        
        // 
        public string BRA009
        {
            get
            {
                return this._bra009;
            }
            set
            {
                this._bra009 = value;
            }
        }
        
        // 
        public string BRA010
        {
            get
            {
                return this._bra010;
            }
            set
            {
                this._bra010 = value;
            }
        }
        
        // 
        public string BRA011
        {
            get
            {
                return this._bra011;
            }
            set
            {
                this._bra011 = value;
            }
        }
        
        // 
        public string BRA012
        {
            get
            {
                return this._bra012;
            }
            set
            {
                this._bra012 = value;
            }
        }
        
        // 
        public string BRA013
        {
            get
            {
                return this._bra013;
            }
            set
            {
                this._bra013 = value;
            }
        }
        
        // 
        public string BRA014
        {
            get
            {
                return this._bra014;
            }
            set
            {
                this._bra014 = value;
            }
        }
        
        // 
        public string BRA015
        {
            get
            {
                return this._bra015;
            }
            set
            {
                this._bra015 = value;
            }
        }
        
        // 
        public string BRA016
        {
            get
            {
                return this._bra016;
            }
            set
            {
                this._bra016 = value;
            }
        }
        
        // 
        public string BRA017
        {
            get
            {
                return this._bra017;
            }
            set
            {
                this._bra017 = value;
            }
        }
        
        // 
        public string BRA018
        {
            get
            {
                return this._bra018;
            }
            set
            {
                this._bra018 = value;
            }
        }
        
        // 
        public string BRA019
        {
            get
            {
                return this._bra019;
            }
            set
            {
                this._bra019 = value;
            }
        }
        
        // 
        public string BRA020
        {
            get
            {
                return this._bra020;
            }
            set
            {
                this._bra020 = value;
            }
        }
    }
}
