//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionErpEntity
{
    using System;
    
    
    public sealed class GeneralAssemblyGEAEntity
    {
        
        private int _idx;
        
        private string _gea001;
        
        private string _gea002;
        
        private string _gea003;
        
        private string _gea004;
        
        private string _gea005;
        
        private string _gea006;
        
        private string _gea007;
        
        private string _gea008;
        
        private string _gea009;
        
        private string _gea010;
        
        private string _gea011;
        
        private string _gea012;
        
        private string _gea013;
        
        private string _gea014;
        
        private string _gea015;
        
        private string _gea016;
        
        private string _gea017;
        
        private string _gea018;
        
        private string _gea019;
        
        private string _gea020;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 条码
        /// </summary>

        public string GEA001
        {
            get
            {
                return this._gea001;
            }
            set
            {
                this._gea001 = value;
            }
        }

        /// <summary>
        /// 品号
        /// </summary>

        public string GEA002
        {
            get
            {
                return this._gea002;
            }
            set
            {
                this._gea002 = value;
            }
        }

        /// <summary>
        /// 品名
        /// </summary>

        public string GEA003
        {
            get
            {
                return this._gea003;
            }
            set
            {
                this._gea003 = value;
            }
        }

        /// <summary>
        /// 规格
        /// </summary>

        public string GEA004
        {
            get
            {
                return this._gea004;
            }
            set
            {
                this._gea004 = value;
            }
        }
        
        /// <summary>
        /// 备注
        /// </summary>
                 
        public string GEA005
        {
            get
            {
                return this._gea005;
            }
            set
            {
                this._gea005 = value;
            }
        }
        
        // 
        public string GEA006
        {
            get
            {
                return this._gea006;
            }
            set
            {
                this._gea006 = value;
            }
        }
        
        // 
        public string GEA007
        {
            get
            {
                return this._gea007;
            }
            set
            {
                this._gea007 = value;
            }
        }
        
        // 
        public string GEA008
        {
            get
            {
                return this._gea008;
            }
            set
            {
                this._gea008 = value;
            }
        }
        
        // 
        public string GEA009
        {
            get
            {
                return this._gea009;
            }
            set
            {
                this._gea009 = value;
            }
        }
        
        // 
        public string GEA010
        {
            get
            {
                return this._gea010;
            }
            set
            {
                this._gea010 = value;
            }
        }
        
        // 
        public string GEA011
        {
            get
            {
                return this._gea011;
            }
            set
            {
                this._gea011 = value;
            }
        }
        
        // 
        public string GEA012
        {
            get
            {
                return this._gea012;
            }
            set
            {
                this._gea012 = value;
            }
        }
        
        // 
        public string GEA013
        {
            get
            {
                return this._gea013;
            }
            set
            {
                this._gea013 = value;
            }
        }
        
        // 
        public string GEA014
        {
            get
            {
                return this._gea014;
            }
            set
            {
                this._gea014 = value;
            }
        }
        
        // 
        public string GEA015
        {
            get
            {
                return this._gea015;
            }
            set
            {
                this._gea015 = value;
            }
        }
        
        // 
        public string GEA016
        {
            get
            {
                return this._gea016;
            }
            set
            {
                this._gea016 = value;
            }
        }
        
        // 
        public string GEA017
        {
            get
            {
                return this._gea017;
            }
            set
            {
                this._gea017 = value;
            }
        }
        
        // 
        public string GEA018
        {
            get
            {
                return this._gea018;
            }
            set
            {
                this._gea018 = value;
            }
        }
        
        // 
        public string GEA019
        {
            get
            {
                return this._gea019;
            }
            set
            {
                this._gea019 = value;
            }
        }
        
        // 
        public string GEA020
        {
            get
            {
                return this._gea020;
            }
            set
            {
                this._gea020 = value;
            }
        }
    }
}
