//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionErpEntity
{
    using System;
    
    
    public sealed class GeneralAssemblyGEBEntity
    {
        
        private int _idx;
        
        private string _geb001;
        
        private string _geb002;
        
        private string _geb003;
        
        private string _geb004;
        
        private string _geb005;
        
        private int _geb006;
        
        private DateTime? _geb007;
        
        private string _geb008;
        
        private string _geb009;
        
        private string _geb010;
        
        private string _geb011;
        
        private string _geb012;
        
        private string _geb013;
        
        private string _geb014;
        
        private string _geb015;
        
        private string _geb016;
        
        private string _geb017;
        
        private string _geb018;
        
        private string _geb019;
        
        private string _geb020;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 条码
        /// </summary>

        public string GEB001
        {
            get
            {
                return this._geb001;
            }
            set
            {
                this._geb001 = value;
            }
        }

        /// <summary>
        /// 工步
        /// </summary>

        public string GEB002
        {
            get
            {
                return this._geb002;
            }
            set
            {
                this._geb002 = value;
            }
        }

        /// <summary>
        /// 记录信息
        /// </summary>

        public string GEB003
        {
            get
            {
                return this._geb003;
            }
            set
            {
                this._geb003 = value;
            }
        }

        /// <summary>
        /// 记录信息
        /// </summary>

        public string GEB004
        {
            get
            {
                return this._geb004;
            }
            set
            {
                this._geb004 = value;
            }
        }

        /// <summary>
        /// 员工姓名
        /// </summary>

        public string GEB005
        {
            get
            {
                return this._geb005;
            }
            set
            {
                this._geb005 = value;
            }
        }

        /// <summary>
        /// 序号
        /// </summary>

        public int GEB006
        {
            get
            {
                return this._geb006;
            }
            set
            {
                this._geb006 = value;
            }
        }
        
        /// <summary>
        /// 填写时间
        /// </summary>
                 
        public DateTime? GEB007
        {
            get
            {
                return this._geb007;
            }
            set
            {
                this._geb007 = value;
            }
        }
        
        // 
        public string GEB008
        {
            get
            {
                return this._geb008;
            }
            set
            {
                this._geb008 = value;
            }
        }
        
        // 
        public string GEB009
        {
            get
            {
                return this._geb009;
            }
            set
            {
                this._geb009 = value;
            }
        }
        
        // 
        public string GEB010
        {
            get
            {
                return this._geb010;
            }
            set
            {
                this._geb010 = value;
            }
        }
        
        // 
        public string GEB011
        {
            get
            {
                return this._geb011;
            }
            set
            {
                this._geb011 = value;
            }
        }
        
        // 
        public string GEB012
        {
            get
            {
                return this._geb012;
            }
            set
            {
                this._geb012 = value;
            }
        }
        
        // 
        public string GEB013
        {
            get
            {
                return this._geb013;
            }
            set
            {
                this._geb013 = value;
            }
        }
        
        // 
        public string GEB014
        {
            get
            {
                return this._geb014;
            }
            set
            {
                this._geb014 = value;
            }
        }
        
        // 
        public string GEB015
        {
            get
            {
                return this._geb015;
            }
            set
            {
                this._geb015 = value;
            }
        }
        
        // 
        public string GEB016
        {
            get
            {
                return this._geb016;
            }
            set
            {
                this._geb016 = value;
            }
        }
        
        // 
        public string GEB017
        {
            get
            {
                return this._geb017;
            }
            set
            {
                this._geb017 = value;
            }
        }
        
        // 
        public string GEB018
        {
            get
            {
                return this._geb018;
            }
            set
            {
                this._geb018 = value;
            }
        }
        
        // 
        public string GEB019
        {
            get
            {
                return this._geb019;
            }
            set
            {
                this._geb019 = value;
            }
        }
        
        // 
        public string GEB020
        {
            get
            {
                return this._geb020;
            }
            set
            {
                this._geb020 = value;
            }
        }
    }
}
