//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionErpEntity
{
    using System;
    
    
    public sealed class SingRowTableSRTEntity
    {
        
        private int _idx;
        
        private string _srt001;
        
        private string _srt002;
        
        private string _srt003;
        
        private string _srt004;
        
        private string _srt005;
        
        private int _srt006;
        
        private string _srt007;
        
        private string _srt008;
        
        private string _srt009;
        
        private string _srt010;
        
        private string _srt011;
        
        private string _srt012;
        
        private string _srt013;
        
        private string _srt014;
        
        private string _srt015;
        
        private string _srt016;
        
        private string _srt017;
        
        private string _srt018;
        
        private string _srt019;
        
        private string _srt020;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 排单号
        /// </summary>

        public string SRT001
        {
            get
            {
                return this._srt001;
            }
            set
            {
                this._srt001 = value;
            }
        }

        /// <summary>
        /// 工单号
        /// </summary>

        public string SRT002
        {
            get
            {
                return this._srt002;
            }
            set
            {
                this._srt002 = value;
            }
        }

        /// <summary>
        /// 品号
        /// </summary>

        public string SRT003
        {
            get
            {
                return this._srt003;
            }
            set
            {
                this._srt003 = value;
            }
        }

        /// <summary>
        /// 品名
        /// </summary>

        public string SRT004
        {
            get
            {
                return this._srt004;
            }
            set
            {
                this._srt004 = value;
            }
        }

        /// <summary>
        /// 规格
        /// </summary>

        public string SRT005
        {
            get
            {
                return this._srt005;
            }
            set
            {
                this._srt005 = value;
            }
        }

        /// <summary>
        /// 数量
        /// </summary>

        public int SRT006
        {
            get
            {
                return this._srt006;
            }
            set
            {
                this._srt006 = value;
            }
        }

        /// <summary>
        /// 定子条码
        /// </summary>

        public string SRT007
        {
            get
            {
                return this._srt007;
            }
            set
            {
                this._srt007 = value;
            }
        }
        
        /// <summary>
        /// 制动器条码
        /// </summary>
                 
        public string SRT008
        {
            get
            {
                return this._srt008;
            }
            set
            {
                this._srt008 = value;
            }
        }
        
        /// <summary>
        /// 总装配条码
        /// </summary>
                 
        public string SRT009
        {
            get
            {
                return this._srt009;
            }
            set
            {
                this._srt009 = value;
            }
        }
        
        // 
        public string SRT010
        {
            get
            {
                return this._srt010;
            }
            set
            {
                this._srt010 = value;
            }
        }
        
        // 
        public string SRT011
        {
            get
            {
                return this._srt011;
            }
            set
            {
                this._srt011 = value;
            }
        }
        
        // 
        public string SRT012
        {
            get
            {
                return this._srt012;
            }
            set
            {
                this._srt012 = value;
            }
        }
        
        // 
        public string SRT013
        {
            get
            {
                return this._srt013;
            }
            set
            {
                this._srt013 = value;
            }
        }
        
        // 
        public string SRT014
        {
            get
            {
                return this._srt014;
            }
            set
            {
                this._srt014 = value;
            }
        }
        
        // 
        public string SRT015
        {
            get
            {
                return this._srt015;
            }
            set
            {
                this._srt015 = value;
            }
        }
        
        // 
        public string SRT016
        {
            get
            {
                return this._srt016;
            }
            set
            {
                this._srt016 = value;
            }
        }
        
        // 
        public string SRT017
        {
            get
            {
                return this._srt017;
            }
            set
            {
                this._srt017 = value;
            }
        }
        
        // 
        public string SRT018
        {
            get
            {
                return this._srt018;
            }
            set
            {
                this._srt018 = value;
            }
        }
        
        // 
        public string SRT019
        {
            get
            {
                return this._srt019;
            }
            set
            {
                this._srt019 = value;
            }
        }
        
        // 
        public string SRT020
        {
            get
            {
                return this._srt020;
            }
            set
            {
                this._srt020 = value;
            }
        }
    }
}
