//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionErpEntity
{
    using System;
    
    
    public sealed class SingRowTableSRVEntity
    {
        
        private int _idx;
        
        private string _srv001;
        
        private string _srv002;
        
        private string _srv003;
        
        private string _srv004;
        
        private string _srv005;
        
        private decimal _srv006;
        
        private string _srv007;
        
        private string _srv008;
        
        private string _srv009;
        
        private string _srv010;
        
        private string _srv011;
        
        private string _srv012;
        
        private string _srv013;
        
        private string _srv014;
        
        private string _srv015;
        
        private string _srv016;
        
        private string _srv017;
        
        private string _srv018;
        
        private string _srv019;
        
        private string _srv020;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 排单号
        /// </summary>

        public string SRV001
        {
            get
            {
                return this._srv001;
            }
            set
            {
                this._srv001 = value;
            }
        }

        /// <summary>
        /// 工单号
        /// </summary>

        public string SRV002
        {
            get
            {
                return this._srv002;
            }
            set
            {
                this._srv002 = value;
            }
        }

        /// <summary>
        /// 品号
        /// </summary>

        public string SRV003
        {
            get
            {
                return this._srv003;
            }
            set
            {
                this._srv003 = value;
            }
        }

        /// <summary>
        /// 品名
        /// </summary>

        public string SRV004
        {
            get
            {
                return this._srv004;
            }
            set
            {
                this._srv004 = value;
            }
        }

        /// <summary>
        /// 规格
        /// </summary>

        public string SRV005
        {
            get
            {
                return this._srv005;
            }
            set
            {
                this._srv005 = value;
            }
        }

        /// <summary>
        /// 数量
        /// </summary>

        public decimal SRV006
        {
            get
            {
                return this._srv006;
            }
            set
            {
                this._srv006 = value;
            }
        }

        /// <summary>
        /// 条码
        /// </summary>

        public string SRV007
        {
            get
            {
                return this._srv007;
            }
            set
            {
                this._srv007 = value;
            }
        }
        
        // 
        public string SRV008
        {
            get
            {
                return this._srv008;
            }
            set
            {
                this._srv008 = value;
            }
        }
        
        // 
        public string SRV009
        {
            get
            {
                return this._srv009;
            }
            set
            {
                this._srv009 = value;
            }
        }
        
        // 
        public string SRV010
        {
            get
            {
                return this._srv010;
            }
            set
            {
                this._srv010 = value;
            }
        }
        
        // 
        public string SRV011
        {
            get
            {
                return this._srv011;
            }
            set
            {
                this._srv011 = value;
            }
        }
        
        // 
        public string SRV012
        {
            get
            {
                return this._srv012;
            }
            set
            {
                this._srv012 = value;
            }
        }
        
        // 
        public string SRV013
        {
            get
            {
                return this._srv013;
            }
            set
            {
                this._srv013 = value;
            }
        }
        
        // 
        public string SRV014
        {
            get
            {
                return this._srv014;
            }
            set
            {
                this._srv014 = value;
            }
        }
        
        // 
        public string SRV015
        {
            get
            {
                return this._srv015;
            }
            set
            {
                this._srv015 = value;
            }
        }
        
        // 
        public string SRV016
        {
            get
            {
                return this._srv016;
            }
            set
            {
                this._srv016 = value;
            }
        }
        
        // 
        public string SRV017
        {
            get
            {
                return this._srv017;
            }
            set
            {
                this._srv017 = value;
            }
        }
        
        // 
        public string SRV018
        {
            get
            {
                return this._srv018;
            }
            set
            {
                this._srv018 = value;
            }
        }
        
        // 
        public string SRV019
        {
            get
            {
                return this._srv019;
            }
            set
            {
                this._srv019 = value;
            }
        }
        
        // 
        public string SRV020
        {
            get
            {
                return this._srv020;
            }
            set
            {
                this._srv020 = value;
            }
        }
    }
}
