//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


namespace ProductionErpEntity
{
    using System;
    
    
    public sealed class SingRowTableSRUEntity
    {
        
        private int _idx;
        
        private string _sru001;
        
        private string _sru002;
        
        private string _sru003;
        
        private string _sru004;
        
        private string _sru005;
        
        private decimal _sru006;
        
        private string _sru007;
        
        private string _sru008;
        
        private string _sru009;
        
        private string _sru010;
        
        private string _sru011;
        
        private string _sru012;
        
        private string _sru013;
        
        private string _sru014;
        
        private string _sru015;
        
        private string _sru016;
        
        private string _sru017;
        
        private string _sru018;
        
        private string _sru019;
        
        private string _sru020;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 排单号
        /// </summary>

        public string SRU001
        {
            get
            {
                return this._sru001;
            }
            set
            {
                this._sru001 = value;
            }
        }

        /// <summary>
        /// 工单号
        /// </summary>

        public string SRU002
        {
            get
            {
                return this._sru002;
            }
            set
            {
                this._sru002 = value;
            }
        }

        /// <summary>
        /// 品号
        /// </summary>

        public string SRU003
        {
            get
            {
                return this._sru003;
            }
            set
            {
                this._sru003 = value;
            }
        }

        /// <summary>
        /// 品名
        /// </summary>

        public string SRU004
        {
            get
            {
                return this._sru004;
            }
            set
            {
                this._sru004 = value;
            }
        }

        /// <summary>
        /// 规格
        /// </summary>

        public string SRU005
        {
            get
            {
                return this._sru005;
            }
            set
            {
                this._sru005 = value;
            }
        }

        /// <summary>
        /// 数量
        /// </summary>

        public decimal SRU006
        {
            get
            {
                return this._sru006;
            }
            set
            {
                this._sru006 = value;
            }
        }

        /// <summary>
        /// 条码
        /// </summary>

        public string SRU007
        {
            get
            {
                return this._sru007;
            }
            set
            {
                this._sru007 = value;
            }
        }
        
        // 
        public string SRU008
        {
            get
            {
                return this._sru008;
            }
            set
            {
                this._sru008 = value;
            }
        }
        
        // 
        public string SRU009
        {
            get
            {
                return this._sru009;
            }
            set
            {
                this._sru009 = value;
            }
        }
        
        // 
        public string SRU010
        {
            get
            {
                return this._sru010;
            }
            set
            {
                this._sru010 = value;
            }
        }
        
        // 
        public string SRU011
        {
            get
            {
                return this._sru011;
            }
            set
            {
                this._sru011 = value;
            }
        }
        
        // 
        public string SRU012
        {
            get
            {
                return this._sru012;
            }
            set
            {
                this._sru012 = value;
            }
        }
        
        // 
        public string SRU013
        {
            get
            {
                return this._sru013;
            }
            set
            {
                this._sru013 = value;
            }
        }
        
        // 
        public string SRU014
        {
            get
            {
                return this._sru014;
            }
            set
            {
                this._sru014 = value;
            }
        }
        
        // 
        public string SRU015
        {
            get
            {
                return this._sru015;
            }
            set
            {
                this._sru015 = value;
            }
        }
        
        // 
        public string SRU016
        {
            get
            {
                return this._sru016;
            }
            set
            {
                this._sru016 = value;
            }
        }
        
        // 
        public string SRU017
        {
            get
            {
                return this._sru017;
            }
            set
            {
                this._sru017 = value;
            }
        }
        
        // 
        public string SRU018
        {
            get
            {
                return this._sru018;
            }
            set
            {
                this._sru018 = value;
            }
        }
        
        // 
        public string SRU019
        {
            get
            {
                return this._sru019;
            }
            set
            {
                this._sru019 = value;
            }
        }
        
        // 
        public string SRU020
        {
            get
            {
                return this._sru020;
            }
            set
            {
                this._sru020 = value;
            }
        }
    }
}
