//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionErpEntity
{
    using System;
    
    
    public sealed class StatorCoilSTDEntity
    {
        
        private int _idx;
        
        private string _std001;
        
        private string _std002;
        
        private string _std003;
        
        private string _std004;
        
        private string _std005;
        
        private int _std006;
        
        private string _std007;
        
        private DateTime? _std008;
        
        private DateTime? _std009;
        
        private string _std010;
        
        private string _std011;
        
        private string _std012;
        
        private string _std013;
        
        private string _std014;
        
        private string _std015;
        
        private string _std016;
        
        private string _std017;
        
        private string _std018;
        
        private string _std019;
        
        private string _std020;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 条码
        /// </summary>

        public string STD001
        {
            get
            {
                return this._std001;
            }
            set
            {
                this._std001 = value;
            }
        }

        /// <summary>
        /// 工序名称
        /// </summary>

        public string STD002
        {
            get
            {
                return this._std002;
            }
            set
            {
                this._std002 = value;
            }
        }

        /// <summary>
        /// 工序内容
        /// </summary>

        public string STD003
        {
            get
            {
                return this._std003;
            }
            set
            {
                this._std003 = value;
            }
        }

        /// <summary>
        /// 测试数据
        /// </summary>

        public string STD004
        {
            get
            {
                return this._std004;
            }
            set
            {
                this._std004 = value;
            }
        }

        /// <summary>
        /// 检验方法
        /// </summary>

        public string STD005
        {
            get
            {
                return this._std005;
            }
            set
            {
                this._std005 = value;
            }
        }

        /// <summary>
        /// 最终工时
        /// </summary>

        public int STD006
        {
            get
            {
                return this._std006;
            }
            set
            {
                this._std006 = value;
            }
        }

        /// <summary>
        /// 签名
        /// </summary>

        public string STD007
        {
            get
            {
                return this._std007;
            }
            set
            {
                this._std007 = value;
            }
        }

        /// <summary>
        /// 日期
        /// </summary>

        public DateTime? STD008
        {
            get
            {
                return this._std008;
            }
            set
            {
                this._std008 = value;
            }
        }
        
        // 
        public DateTime? STD009
        {
            get
            {
                return this._std009;
            }
            set
            {
                this._std009 = value;
            }
        }
        
        /// <summary>
        /// 
        /// </summary>
                 
        public string STD010
        {
            get
            {
                return this._std010;
            }
            set
            {
                this._std010 = value;
            }
        }
        
        /// <summary>
        /// 
        /// </summary>
                 
        public string STD011
        {
            get
            {
                return this._std011;
            }
            set
            {
                this._std011 = value;
            }
        }

        /// <summary>
        /// 嵌线人员
        /// </summary>

        public string STD012
        {
            get
            {
                return this._std012;
            }
            set
            {
                this._std012 = value;
            }
        }

        /// <summary>
        /// 不合格项
        /// </summary>

        public string STD013
        {
            get
            {
                return this._std013;
            }
            set
            {
                this._std013 = value;
            }
        }
        
        // 
        public string STD014
        {
            get
            {
                return this._std014;
            }
            set
            {
                this._std014 = value;
            }
        }
        
        // 
        public string STD015
        {
            get
            {
                return this._std015;
            }
            set
            {
                this._std015 = value;
            }
        }
        
        // 
        public string STD016
        {
            get
            {
                return this._std016;
            }
            set
            {
                this._std016 = value;
            }
        }
        
        // 
        public string STD017
        {
            get
            {
                return this._std017;
            }
            set
            {
                this._std017 = value;
            }
        }
        
        // 
        public string STD018
        {
            get
            {
                return this._std018;
            }
            set
            {
                this._std018 = value;
            }
        }
        
        // 
        public string STD019
        {
            get
            {
                return this._std019;
            }
            set
            {
                this._std019 = value;
            }
        }
        
        // 
        public string STD020
        {
            get
            {
                return this._std020;
            }
            set
            {
                this._std020 = value;
            }
        }
    }
}
