//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionErpEntity
{
    using System;
    
    
    public sealed class StatorCoilSTCEntity
    {
        
        private int _idx;
        
        private string _stc001;
        
        private int _stc002;
        
        private string _stc003;
        
        private string _stc004;
        
        private int _stc005;
        
        private string _stc006;
        
        private string _stc007;
        
        private string _stc008;
        
        private string _stc009;
        
        private string _stc010;
        
        private string _stc011;
        
        private string _stc012;
        
        private string _stc013;
        
        private string _stc014;
        
        private string _stc015;
        
        private string _stc016;
        
        private string _stc017;
        
        private string _stc018;
        
        private string _stc019;
        
        private string _stc020;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 条码
        /// </summary>

        public string STC001
        {
            get
            {
                return this._stc001;
            }
            set
            {
                this._stc001 = value;
            }
        }

        /// <summary>
        /// 电压
        /// </summary>

        public int STC002
        {
            get
            {
                return this._stc002;
            }
            set
            {
                this._stc002 = value;
            }
        }

        /// <summary>
        /// 派工单号
        /// </summary>

        public string STC003
        {
            get
            {
                return this._stc003;
            }
            set
            {
                this._stc003 = value;
            }
        }

        /// <summary>
        /// 规格
        /// </summary>

        public string STC004
        {
            get
            {
                return this._stc004;
            }
            set
            {
                this._stc004 = value;
            }
        }

        /// <summary>
        /// 铁芯长度
        /// </summary>

        public int STC005
        {
            get
            {
                return this._stc005;
            }
            set
            {
                this._stc005 = value;
            }
        }

        /// <summary>
        /// 铁芯钢印号
        /// </summary>
        
        public string STC006
        {
            get
            {
                return this._stc006;
            }
            set
            {
                this._stc006 = value;
            }
        }
        
        /// <summary>
        /// 人员编号
        /// </summary>
        public string STC007
        {
            get
            {
                return this._stc007;
            }
            set
            {
                this._stc007 = value;
            }
        }
        
        /// <summary>
        /// 人员姓名
        /// </summary>            
        public string STC008
        {
            get
            {
                return this._stc008;
            }
            set
            {
                this._stc008 = value;
            }
        }
        
        // 
        public string STC009
        {
            get
            {
                return this._stc009;
            }
            set
            {
                this._stc009 = value;
            }
        }
        
        // 
        public string STC010
        {
            get
            {
                return this._stc010;
            }
            set
            {
                this._stc010 = value;
            }
        }
        
        // 
        public string STC011
        {
            get
            {
                return this._stc011;
            }
            set
            {
                this._stc011 = value;
            }
        }
        
        // 
        public string STC012
        {
            get
            {
                return this._stc012;
            }
            set
            {
                this._stc012 = value;
            }
        }
        
        // 
        public string STC013
        {
            get
            {
                return this._stc013;
            }
            set
            {
                this._stc013 = value;
            }
        }
        
        // 
        public string STC014
        {
            get
            {
                return this._stc014;
            }
            set
            {
                this._stc014 = value;
            }
        }
        
        // 
        public string STC015
        {
            get
            {
                return this._stc015;
            }
            set
            {
                this._stc015 = value;
            }
        }
        
        // 
        public string STC016
        {
            get
            {
                return this._stc016;
            }
            set
            {
                this._stc016 = value;
            }
        }
        
        // 
        public string STC017
        {
            get
            {
                return this._stc017;
            }
            set
            {
                this._stc017 = value;
            }
        }
        
        // 
        public string STC018
        {
            get
            {
                return this._stc018;
            }
            set
            {
                this._stc018 = value;
            }
        }
        
        // 
        public string STC019
        {
            get
            {
                return this._stc019;
            }
            set
            {
                this._stc019 = value;
            }
        }
        
        // 
        public string STC020
        {
            get
            {
                return this._stc020;
            }
            set
            {
                this._stc020 = value;
            }
        }
    }
}
