//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionErpEntity
{
    using System;
    
    
    public sealed class StorageMaterialEntity
    {
        
        private int _idx;
        
        private string _stm001;
        
        private string _stm002;
        
        private string _stm003;
        
        private string _stm004;
        
        private string _stm005;
        
        private string _stm006;
        
        private string _stm007;
        
        private string _stm008;
        
        private string _stm009;
        
        private string _stm010;
        
        private string _stm011;
        
        private string _stm012;
        
        private string _stm013;
        
        private string _stm014;
        
        private string _stm015;
        
        private string _stm016;
        
        private string _stm017;
        
        private string _stm018;
        
        private string _stm019;
        
        private string _stm020;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 进货单号
        /// </summary>

        public string STM001
        {
            get
            {
                return this._stm001;
            }
            set
            {
                this._stm001 = value;
            }
        }

        /// <summary>
        /// 序号
        /// </summary>

        public string STM002
        {
            get
            {
                return this._stm002;
            }
            set
            {
                this._stm002 = value;
            }
        }

        /// <summary>
        /// 品号
        /// </summary>

        public string STM003
        {
            get
            {
                return this._stm003;
            }
            set
            {
                this._stm003 = value;
            }
        }

        /// <summary>
        /// 品名
        /// </summary>

        public string STM004
        {
            get
            {
                return this._stm004;
            }
            set
            {
                this._stm004 = value;
            }
        }

        /// <summary>
        /// 规格
        /// </summary>

        public string STM005
        {
            get
            {
                return this._stm005;
            }
            set
            {
                this._stm005 = value;
            }
        }


        /// <summary>
        /// 条码
        /// </summary>
        public string STM006
        {
            get
            {
                return this._stm006;
            }
            set
            {
                this._stm006 = value;
            }
        }

        /// <summary>
        /// 使用状态
        /// </summary>

        public string STM007
        {
            get
            {
                return this._stm007;
            }
            set
            {
                this._stm007 = value;
            }
        }
        
        // 
        public string STM008
        {
            get
            {
                return this._stm008;
            }
            set
            {
                this._stm008 = value;
            }
        }
        
        // 
        public string STM009
        {
            get
            {
                return this._stm009;
            }
            set
            {
                this._stm009 = value;
            }
        }
        
        // 
        public string STM010
        {
            get
            {
                return this._stm010;
            }
            set
            {
                this._stm010 = value;
            }
        }
        
        // 
        public string STM011
        {
            get
            {
                return this._stm011;
            }
            set
            {
                this._stm011 = value;
            }
        }
        
        // 
        public string STM012
        {
            get
            {
                return this._stm012;
            }
            set
            {
                this._stm012 = value;
            }
        }
        
        // 
        public string STM013
        {
            get
            {
                return this._stm013;
            }
            set
            {
                this._stm013 = value;
            }
        }
        
        // 
        public string STM014
        {
            get
            {
                return this._stm014;
            }
            set
            {
                this._stm014 = value;
            }
        }
        
        // 
        public string STM015
        {
            get
            {
                return this._stm015;
            }
            set
            {
                this._stm015 = value;
            }
        }
        
        // 
        public string STM016
        {
            get
            {
                return this._stm016;
            }
            set
            {
                this._stm016 = value;
            }
        }
        
        // 
        public string STM017
        {
            get
            {
                return this._stm017;
            }
            set
            {
                this._stm017 = value;
            }
        }
        
        // 
        public string STM018
        {
            get
            {
                return this._stm018;
            }
            set
            {
                this._stm018 = value;
            }
        }
        
        // 
        public string STM019
        {
            get
            {
                return this._stm019;
            }
            set
            {
                this._stm019 = value;
            }
        }
        
        // 
        public string STM020
        {
            get
            {
                return this._stm020;
            }
            set
            {
                this._stm020 = value;
            }
        }
    }
}
