//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionErpEntity
{
    using System;
    
    
    public sealed class WindingWIEEntity
    {
        
        private int _idx;
        
        private string _wie001;
        
        private string _wie002;
        
        private string _wie003;
        
        private DateTime? _wie004;
        
        private string _wie005;
        
        private int? _wie006;
        
        private string _wie007;
        
        private int _wie008;
        
        private int _wie009;
        
        private decimal _wie010;
        
        private string _wie011;
        
        private string _wie012;
        
        private int _wie013;
        
        private int _wie014;
        
        private string _wie015;
        
        private DateTime? _wie016;
        
        private string _wie017;
        
        private string _wie018;
        
        private string _wie019;
        
        private string _wie020;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 单号
        /// </summary>

        public string WIE001
        {
            get
            {
                return this._wie001;
            }
            set
            {
                this._wie001 = value;
            }
        }

        /// <summary>
        /// 品号
        /// </summary>

        public string WIE002
        {
            get
            {
                return this._wie002;
            }
            set
            {
                this._wie002 = value;
            }
        }

        /// <summary>
        /// 规格
        /// </summary>

        public string WIE003
        {
            get
            {
                return this._wie003;
            }
            set
            {
                this._wie003 = value;
            }
        }

        /// <summary>
        /// 生产时间
        /// </summary>

        public DateTime? WIE004
        {
            get
            {
                return this._wie004;
            }
            set
            {
                this._wie004 = value;
            }
        }

        /// <summary>
        /// 批号
        /// </summary>

        public string WIE005
        {
            get
            {
                return this._wie005;
            }
            set
            {
                this._wie005 = value;
            }
        }

        /// <summary>
        /// 数量
        /// </summary>

        public int? WIE006
        {
            get
            {
                return this._wie006;
            }
            set
            {
                this._wie006 = value;
            }
        }

        /// <summary>
        /// 品质部签字(换线规时）
        /// </summary>

        public string WIE007
        {
            get
            {
                return this._wie007;
            }
            set
            {
                this._wie007 = value;
            }
        }

        /// <summary>
        /// 工作时间(同一规格）
        /// </summary>

        public int WIE008
        {
            get
            {
                return this._wie008;
            }
            set
            {
                this._wie008 = value;
            }
        }

        /// <summary>
        /// 平均时间（同一规格）
        /// </summary>

        public int WIE009
        {
            get
            {
                return this._wie009;
            }
            set
            {
                this._wie009 = value;
            }
        }

        /// <summary>
        ///  重量(KG)
        /// </summary>
        public decimal WIE010
        {
            get
            {
                return this._wie010;
            }
            set
            {
                this._wie010 = value;
            }
        }
        
        /// <summary>
        /// 人员编号
        /// </summary>
                 
        public string WIE011
        {
            get
            {
                return this._wie011;
            }
            set
            {
                this._wie011 = value;
            }
        }

        /// <summary>
        /// 人员姓名
        /// </summary>

        public string WIE012
        {
            get
            {
                return this._wie012;
            }
            set
            {
                this._wie012 = value;
            }
        }

        /// <summary>
        /// 接头数量
        /// </summary>
        public int WIE013
        {
            get
            {
                return this._wie013;
            }
            set
            {
                this._wie013 = value;
            }
        }

        /// <summary>
        /// 最终工时
        /// </summary>
        public int WIE014
        {
            get
            {
                return this._wie014;
            }
            set
            {
                this._wie014 = value;
            }
        }

        /// <summary>
        /// 签名
        /// </summary>
        public string WIE015
        {
            get
            {
                return this._wie015;
            }
            set
            {
                this._wie015 = value;
            }
        }

        /// <summary>
        /// 日期
        /// </summary>
        public DateTime? WIE016
        {
            get
            {
                return this._wie016;
            }
            set
            {
                this._wie016 = value;
            }
        }
        
        // 
        public string WIE017
        {
            get
            {
                return this._wie017;
            }
            set
            {
                this._wie017 = value;
            }
        }
        
        // 
        public string WIE018
        {
            get
            {
                return this._wie018;
            }
            set
            {
                this._wie018 = value;
            }
        }
        
        // 
        public string WIE019
        {
            get
            {
                return this._wie019;
            }
            set
            {
                this._wie019 = value;
            }
        }
        
        // 
        public string WIE020
        {
            get
            {
                return this._wie020;
            }
            set
            {
                this._wie020 = value;
            }
        }
    }
}
