//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionErpEntity
{
    using System;
    
    
    public sealed class WindingWIDEntity
    {
        
        private int _idx;
        
        private string _wid001;
        
        private string _wid002;
        
        private string _wid003;
        
        private string _wid004;
        
        private DateTime _wid005;
        
        private string _wid006;
        
        private string _wid007;
        
        private string _wid008;
        
        private string _wid009;
        
        private string _wid010;
        
        private string _wid011;
        
        private string _wid012;
        
        private string _wid013;
        
        private string _wid014;
        
        private string _wid015;
        
        private string _wid016;
        
        private string _wid017;
        
        private string _wid018;
        
        private string _wid019;
        
        private string _wid020;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 单号
        /// </summary>

        public string WID001
        {
            get
            {
                return this._wid001;
            }
            set
            {
                this._wid001 = value;
            }
        }

        /// <summary>
        /// 排单号
        /// </summary>

        public string WID002
        {
            get
            {
                return this._wid002;
            }
            set
            {
                this._wid002 = value;
            }
        }

        /// <summary>
        /// 人员编号
        /// </summary>

        public string WID003
        {
            get
            {
                return this._wid003;
            }
            set
            {
                this._wid003 = value;
            }
        }

        /// <summary>
        /// 人员姓名
        /// </summary>

        public string WID004
        {
            get
            {
                return this._wid004;
            }
            set
            {
                this._wid004 = value;
            }
        }

        /// <summary>
        /// 派工时间
        /// </summary>

        public DateTime WID005
        {
            get
            {
                return this._wid005;
            }
            set
            {
                this._wid005 = value;
            }
        }
        
        // 
        public string WID006
        {
            get
            {
                return this._wid006;
            }
            set
            {
                this._wid006 = value;
            }
        }
        
        // 
        public string WID007
        {
            get
            {
                return this._wid007;
            }
            set
            {
                this._wid007 = value;
            }
        }
        
        // 
        public string WID008
        {
            get
            {
                return this._wid008;
            }
            set
            {
                this._wid008 = value;
            }
        }
        
        // 
        public string WID009
        {
            get
            {
                return this._wid009;
            }
            set
            {
                this._wid009 = value;
            }
        }
        
        // 
        public string WID010
        {
            get
            {
                return this._wid010;
            }
            set
            {
                this._wid010 = value;
            }
        }
        
        // 
        public string WID011
        {
            get
            {
                return this._wid011;
            }
            set
            {
                this._wid011 = value;
            }
        }
        
        // 
        public string WID012
        {
            get
            {
                return this._wid012;
            }
            set
            {
                this._wid012 = value;
            }
        }
        
        // 
        public string WID013
        {
            get
            {
                return this._wid013;
            }
            set
            {
                this._wid013 = value;
            }
        }
        
        // 
        public string WID014
        {
            get
            {
                return this._wid014;
            }
            set
            {
                this._wid014 = value;
            }
        }
        
        // 
        public string WID015
        {
            get
            {
                return this._wid015;
            }
            set
            {
                this._wid015 = value;
            }
        }
        
        // 
        public string WID016
        {
            get
            {
                return this._wid016;
            }
            set
            {
                this._wid016 = value;
            }
        }
        
        // 
        public string WID017
        {
            get
            {
                return this._wid017;
            }
            set
            {
                this._wid017 = value;
            }
        }
        
        // 
        public string WID018
        {
            get
            {
                return this._wid018;
            }
            set
            {
                this._wid018 = value;
            }
        }
        
        // 
        public string WID019
        {
            get
            {
                return this._wid019;
            }
            set
            {
                this._wid019 = value;
            }
        }
        
        // 
        public string WID020
        {
            get
            {
                return this._wid020;
            }
            set
            {
                this._wid020 = value;
            }
        }
    }
}
